- src/pages/Payment/Payment.js
- src/pages/Payment/Payment.scss
- src/pages/Payment/components/Agreement.js
- src/pages/Payment/components/Agreement.scss
- src/pages/Payment/components/OrderList.js
- src/pages/Payment/components/OrderList.scss
- src/pages/Payment/components/Orderer.js
- src/pages/Payment/components/Orderer.scss
- src/pages/Payment/components/PaymentInfo.js
- src/pages/Payment/components/PaymentInfo.scss
- src/pages/Payment/components/PaymentMethod.js
- src/pages/Payment/components/PaymentMethod.scss
- src/pages/Payment/components/Shipment.js
- src/pages/Payment/components/Shipment.scss
- src/pages/Payment/components/ShipmentSelect.js
- src/pages/Payment/components/ShipmentSelect.scss
- src/pages/Payment/components/Subscribe.js
- src/pages/Payment/components/Subscribe.scss
<br />
---
<br />
- 고객이 상품을 구입하기위해 결제하는 페이지를 보여준다. 
- 주문제품, 주문자 정보, 배송 정보, 정기배송 시작일, 결제 수단 등을 확인한다.
- 결제정보에서 주문 제품 금액과 배송비가 합계된 총 결제금액을 볼 수 있다.
<br />
결제페이지 레이아웃 구현
- 주문제품에서 주문제품 리스트 구현
- 주문자 정보에서 주문자 이름, 번호, 이메일 구현
- 배송 정보에서 배송지, 받는사람, 주소, 번호, 요청사항(select) 구현
<br />
<br />
<br />
- 각 컴포넌트를 분리할 수 있었습니다.
- 라디오 input을 사용할 수 있었습니다.
- 페이지 레이아웃을 할 수 있었습니다.
- 상수데이터를 매핑해서 반복적으로 사용할 수 있었습니다.
- 상수데이터에 대한 상태를 고려하도록 구현할 수 있었습니다.
<br />
> [45기 박현아] ADD : payment 페이지 레이아웃

- src/pages/Login/Login.js
- src/pages/Login/Login.scss
- src/pages/Signup/Signup.js
- src/styles/reset.scss
<br />
---
<br />
<br />
<br />
- 로그인을 함으로써 메인 페이지로 들어갈 수 있습니다.
- 로그인을 할 수 있습니다.
<br />
로그인 레이아웃 구현
- 로그인 레이아웃 구현
<br />
<br />
-
<br />
- display flex에 대한 …
> [45기 이소진] Add : 로그인 래이아웃 구현

- src/styles/reset.scss
reset.scss 파일의 
body {
line-height 1} 부분으로 인해 푸터 스타일을 줄수 없어 긴급히 머지 요청드립니다.
> Modify : !긴급스타일수정사항!

- src/pages/Signup/Signup.js
- src/pages/Signup/Signup.scss
<br />
---
<br />
-  고객이 처음 들어왔을 때 회원 가입을 할 수 있습니다.
-회원이 쉽게 회원 가입을 할 수 있습니다.
<br />
- 
<br />
- id, class 선택자에 대해 조금 더 이해할 수 있었습니다.
<br />
> [45기 이소진] Add : 회원가입 레이아웃 구현

- src/pages/Login/Login.js
- src/pages/Login/Login.scss
- src/styles/reset.scss
<br />
---
<br />
- 고객의 유입과 전환을 책임지는 회원 기능에서, 유저의 이탈을 방지하기 위해 아이디를 입력하지 않거나 유효성 검사에 걸리는 경우 이메일을 다시 입력해 달라고 알림창을 띄우고 비밀번호를 입력하지 않은 경우 비밀번호를 입력해달라고 알림창이 뜹니다. 
-  유저는 실시간으로 스스로 오기입한 내용을 확인할 수 있기 때문에 잘못 계정 정보를 작성함으로써 발생될 수 있는 변수를 최소화할 수 있습니다. 이는 곧 유저 전환의 허들을 낮추어 줄 수 있습니다.
<br />
로그인 기능 추가
- 소문자 문자(a-z)나 숫자(0-9) 중 하나 이상으로 시작해야 합니다.
그 다음, “@” 기호가 있어야 합니다.
“@” 뒤에는 소문자 문자(a-z) 중 하나 이상이 있어야 합니다.
그 다음, “.” 기호가 있어야 합니다.
마지막으로, 최상위 도메인(TLD)을 나타내는 “.com”, “.org”, “.edu”와 같은 소문자 문자(a-z) 2개 또는 3개가 있어야 하는 유효성 검사 추가 
-  유효성 검사 통과하지 못할 때  이메일을 다시 입력해주세요 혹은 비밀번호를 입력해주세요 …
> [45기 이소진] Add : 로그인 기능 구현

- src/pages/Details/Details.js
<br />
---
<br />
<br />
<br /> …
> [45기 김희연] config import 파일명 수정본 

- src/pages/Login/Login.js
- src/pages/Login/Login.scss
<br />
---
<br />
<br />
<br /> …
> [45기 이소진]  Add : 로그인 기능 구현

- src/pages/Login/Login.js
- src/pages/Login/Login.scss
- src/pages/Signup/Signup.js
- src/pages/Signup/Signup.scss
<br />
---
<br />
<br />
<br /> …
> [45기 이소진] Add : 아이디, 회원가입 페이지  로고 추가

- src/Router.js
- src/components/CategoryModal/CategoryModal.js
- src/components/CategoryModal/CategoryModalNav.js
- src/components/Footer/Footer.js
- src/components/Footer/Footer.scss
- src/components/Header/Header.js
- src/pages/Details/Mainlayout.js
- src/pages/Main/Main.js
- src/pages/Main/Main.scss
- src/pages/Main/components/NewestNav.scss
- src/pages/Main/components/NewestPrdouct.scss
<br />
---
<br />
<br />
<br /> …
> Add : 헤더 푸터 연결, scss풀리는 현상 해결

- src/pages/Details/components/Button.scss
- src/pages/Details/components/Contents.js
- src/pages/Details/components/SubscribeOptions.js
<br />
---
<br />
<br />
<br /> …
> [45기 김희연] 상품디테일 페이지 품절 표시 추가

- src/pages/Login/Login.js
- src/pages/Signup/Signup.js
- src/pages/Signup/Signup.scss
<br />
---
<br />
<br />
<br /> …
> [이소진] Add : 회원가입 알림창 추가

- src/pages/Details/Details.js
- src/pages/Details/Details.scss
- src/pages/Details/components/Contents.js
<br />
---
<br />
<br />
<br /> …
> [45기 김희연]  상품디테일 레이아웃 일부 수정, 장바구니 버튼 로직 수정

- src/pages/Cart/Cart.js
- src/pages/Cart/Components/LeftSide.js
- src/pages/Cart/Components/ProductItem.js
<br />
---
<br />
<br />
<br /> …
> [45기 오승민] Modify :  장바구니 페이지 기능 수정

- src/pages/Details/Mainlayout.js
- src/pages/Main/components/ProductLineup.js
> [45기 김준섭] Add: 장바구니, 결제페이지, 마이페이지일때 로그아웃버튼 클릭시 메인페이지로 가는 기능 구현

- src/pages/Login/Login.js
- src/pages/Signup/Signup.js
<br />
---
<br />
<br />
<br /> …
> [45기 이소진] Modify  : 체크박스 필수 사항 체크 안할 시 알림창 설정

- src/pages/Login/Login.js
<br />
---
<br />
<br />
<br /> …
> [45기 이소진] Modify : 로그인 페이지 수정

- src/components/Nav/NavMain.js
- src/components/TitleLine/TitleLine.js
- src/pages/Cart/Cart.js
- src/pages/Cart/Components/Blank.js
- src/pages/Cart/Components/LeftSide.js
- src/pages/Cart/Components/RightSide.scss
- src/pages/Details/components/Button.scss
- src/pages/Details/components/Review.js
- src/pages/Login/Login.js
- src/pages/Login/Login.scss
- src/pages/Main/components/ProductLineup.js
- src/pages/Signup/Signup.js
- src/pages/Signup/Signup.scss
<br />
---
<br />
<br />
<br /> …
> [45기 이소진] Modify : Debug1 

- src/pages/Cart/Cart.js
- src/pages/Login/Login.js
- src/pages/Mypage/Mypage.js
- src/pages/Mypage/Mypage.scss
- src/pages/Mypage/components/ConfirmPassword.scss
- src/pages/Mypage/components/LikesProduct.js
- src/pages/Mypage/components/MenuBar.scss
- src/pages/Mypage/components/SubscribesProduct.js
- src/pages/Payment/OrderCompleted.js
- src/pages/Payment/Payment.js
<br />
---
<br />
<br />
<br /> …
> [45기 A조] Modify : 자잘한 수정사항 반영

- src/pages/Mypage/Mypage.js
- src/pages/Mypage/components/ConfirmPassword.js
- src/pages/Mypage/components/ConfirmPassword.scss
- src/pages/Mypage/components/LikesList.js
- src/pages/Mypage/components/OrderDelivery.js
- src/pages/Mypage/components/OrderItems.js
- src/pages/Mypage/components/OrderProducts.js
- src/pages/Mypage/components/OrderProducts.scss
- src/pages/Mypage/components/OrderStatus.js
- src/pages/Mypage/components/Subscribes.js
- src/pages/Payment/Payment.js
<br />
---
<br />
<br />
<br /> …
> [45기 박현아] Modif: 마이페이지 오류 수정

- src/components/TitleLine/TitleLine.js
- src/pages/Mypage/Mypage.js
<br />
---
<br />
<br />
<br /> …
> Modif: TitleLine에서 하트버튼으로 관심상품가기

- src/pages/Mypage/components/LikesList.js
<br />
---
<br />
<br />
<br /> …
> [45기 박현아] Modif: 관심상품 선택삭제 가능

- src/pages/Details/components/CartModal.scss
- src/pages/Details/components/CartRecheckModal.scss
<br />
---
<br />
<br />
<br /> …
> [45기 김희연] 상품상세페이지 레이아웃 변경

- src/pages/Signup/Signup.js
<br />
---
<br />
<br />
<br /> …
> [45기 이소진] Modify : 전화번호 형식으로 입력하지 않으면 다시 입력해달라고 알림창 나오게 수정

- src/components/Header/Header.js
- src/pages/Mypage/Mypage.js
- src/pages/Mypage/components/CustomerService.js
- src/pages/Mypage/components/CustomerService.scss
- src/pages/Mypage/components/LikesProduct.js
- src/pages/Mypage/components/LikesProduct.scss
- src/pages/Mypage/components/MenuBar.js
<br />
---
<br />
<br />
<br /> …
> [45기 박현아] Add: 고객센터 추가

- src/pages/Details/Details.js
- src/pages/Details/components/Contents.js
<br />
---
<br />
<br />
<br /> …
> [45기 김희연] wishbutton 수정

- src/pages/Details/components/Contents.js
- src/pages/Payment/Payment.js
<br />
---
<br />
<br />
<br /> …
> [45기 박현아] Modif: 오타수정

- src/config.js
- src/pages/Cart/Cart.js
- src/pages/Cart/Components/LeftSide.js
- src/pages/Details/Details.js
- src/pages/Details/components/Contents.js
- src/pages/Details/components/ProductInformation.scss
- src/pages/Details/components/ReviewList.js
- src/pages/Details/components/WishlistButton.js
- src/pages/Login/Login.js
- src/pages/Main/Main.js
- src/pages/Main/components/ProductLineup.scss
- src/pages/Mypage/Mypage.js
- src/pages/Mypage/components/ConfirmPassword.js
- src/pages/Mypage/components/Likes.js
- src/pages/Mypage/components/LikesList.js
- src/pages/Mypage/components/LikesProduct.js
- src/pages/Mypage/components/Subscribes.js
- src/pages/Mypage/components/UserInfoUpdate.js
- src/pages/Payment/Payment.js
- src/pages/Signup/Signup.js
<br />
---
<br />
<br />
<br /> …
> Add : AWS 어드레스로 교체

- src/config.js
- src/pages/ProductList/components/ProdcutListCont.js
<br />
---
<br />
<br />
<br /> …
> Modify : 페이지네이션 오류 해결

- src/components/Footer/Footer.js
- src/pages/Mypage/Mypage.js
- src/pages/Mypage/Mypage.scss
- src/pages/Mypage/components/ConfirmPassword.js
- src/pages/Mypage/components/ConfirmPassword.scss
- src/pages/Mypage/components/Likes.js
- src/pages/Mypage/components/LikesList.js
- src/pages/Mypage/components/MenuBar.js
- src/pages/Mypage/components/MypageTop.js
- src/pages/Mypage/components/OrderDelivery.js
- src/pages/Mypage/components/OrderItems.js
- src/pages/Mypage/components/OrderItems.scss
- src/pages/Mypage/components/OrderProducts.scss
- src/pages/Mypage/components/OrderStatus.js
- src/pages/Mypage/components/UserInfoUpdate.js
- src/pages/Mypage/components/UserInfoUpdate.scss
- src/pages/Payment/OrderCompleted.js
- src/pages/Payment/OrderCompleted.scss
- src/pages/Payment/Payment.js
- src/pages/Payment/components/Agreement.scss
- src/pages/Payment/components/OrderList.js
- src/pages/Payment/components/PaymentMethod.js
- src/pages/Payment/components/PaymentMethod.scss
- src/pages/Payment/components/Shipment.js
- src/pages/Payment/components/ShipmentSelect.js
- src/pages/Signup/Signup.js
<br />
---
<br />
<br />
<br /> …
> [45기 박현아] Modif: 오류수정

- src/pages/Payment/Payment.js
- src/pages/Payment/components/Shipment.js
<br />
---
<br />
<br />
<br /> …
> Add: 휴대폰 번호 정규식

- src/pages/ProductList/components/ProdcutListCont.js
<br />
---
<br />
<br />
<br /> …
> [45기 김준섭]리디렉션시 오류환경 해결
